---
- name: Create directory
  file:
    path: ~/web
    state: directory

# - name: Copy artifacts zip
#   template:
#     src: "files/artifact.tar.gz"
#     dest: "~/web/artifact.tar.gz"

- name: Copy artifacts zip
  copy: 
    src: ~/project/artifact.tar.gz
    dest: ~/web/artifact.tar.gz

- name: Untar artifact 
  shell: |
    cd ~/web
    mkdir backend
    cd backend
    tar -xzvf ../artifact.tar.gz


- name: Start application
  become: true
  shell: |
    cd ~/web/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    